python3 experiment_EA.py --DATASET 00 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 00 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 00 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 00 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 00 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 00 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 00 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 00 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 00 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 00 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 01 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 01 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 01 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 01 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 01 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 01 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 01 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 01 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 01 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 01 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 02 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 02 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 02 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 02 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 02 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 02 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 02 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 02 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 02 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 02 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 03 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 03 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 03 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 03 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 03 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 03 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 03 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 03 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 03 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 03 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 04 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 04 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 04 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 04 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 04 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 04 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 04 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 04 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 04 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 04 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 05 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 05 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 05 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 05 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 05 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 05 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 05 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 05 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 05 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 05 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 06 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 06 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 06 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 06 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 06 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 06 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 06 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 06 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 06 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 06 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 07 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 07 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 07 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 07 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 07 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 07 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 07 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 07 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 07 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 07 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 08 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 08 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 08 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 08 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 08 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 08 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 08 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 08 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 08 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 08 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 09 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 09 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 09 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 09 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 09 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 09 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 09 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 09 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 09 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 09 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 10 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 10 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 10 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 10 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 10 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 10 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 10 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 10 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 10 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 10 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 11 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 11 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 11 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 11 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 11 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 11 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 11 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 11 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 11 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 11 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 12 --SEED 00 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 12 --SEED 01 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 12 --SEED 02 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 12 --SEED 03 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 12 --SEED 04 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 12 --SEED 05 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 12 --SEED 06 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 12 --SEED 07 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 12 --SEED 08 --e_train 0.05 --projectname VariationAware_EA &
python3 experiment_EA.py --DATASET 12 --SEED 09 --e_train 0.05 --projectname VariationAware_EA &
