sbatch 6.1_final_INV_model.py 1
sbatch 6.1_final_INV_model.py 2
sbatch 6.1_final_INV_model.py 3
sbatch 6.1_final_INV_model.py 4
sbatch 6.1_final_INV_model.py 5
sbatch 6.1_final_INV_model.py 6
sbatch 6.1_final_INV_model.py 7
sbatch 6.1_final_INV_model.py 8
sbatch 6.1_final_INV_model.py 9
sbatch 6.1_final_INV_model.py 10