sbatch 5.1_final_ACTPOW_model.py 1
sbatch 5.1_final_ACTPOW_model.py 2
sbatch 5.1_final_ACTPOW_model.py 3
sbatch 5.1_final_ACTPOW_model.py 4
sbatch 5.1_final_ACTPOW_model.py 5
sbatch 5.1_final_ACTPOW_model.py 6
sbatch 5.1_final_ACTPOW_model.py 7
sbatch 5.1_final_ACTPOW_model.py 8
sbatch 5.1_final_ACTPOW_model.py 9
sbatch 5.1_final_ACTPOW_model.py 10